adding elastic-operator pack
spectrocloud/pack-central pull request #78
Opened 2024-05-19 20:18 UTC by JPedro2

2024-05-19 20:20 UTC, JPedro2 commented
Elastic Operator Helm chart v2.12.1 added as a pack, without any presets but with updated version of README (adapted to be used with the pack) and with k8s min. version dependency only

2024-05-20 18:37 UTC, vishwanaths requested changes
Please include the elastic-operator chart in the pack.
Also in the values.yaml, under charts: have the entry by name of the chart and have the rest of them nested under it.

2024-05-23 17:52 UTC, vishwanaths approved these changes

2024-05-23 18:03 UTC, zulfilee approved these changes

2024-05-23 18:14 UTC, merged