adding elastic-stack pack
spectrocloud/pack-central pull request #79
Opened 2024-05-19 20:40 UTC by JPedro2

2024-05-20 15:38 UTC, vishwanaths requested changes

2024-05-20 18:35 UTC, vishwanaths requested changes

2024-05-20 18:35 UTC, vishwanaths commented on packs/elastic-stack-0.10.0/values.yaml
eck-stack is the top level chart, rest of them needs to be nested under it
pack:
  content:
    images:
      - image: docker.elastic.co/kibana/kibana:8.13.0
      - image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0

    charts:
      - repo: https://helm.elastic.co/
        name: eck-stack
        version: 0.10.0
  #The namespace (on the target cluster) to install this chart
  #When not found, a new namespace will be created
  namespace: "elastic-stack"

charts:
  eck-stack:
     # If enabled, will use the eck-elasticsearch chart and deploy an Elasticsearch resource.
      #
      eck-elasticsearch:
        enabled: true
        # This is adjusting the full name of the elasticsearch resource so that both the eck-elasticsearch
        # and the eck-kibana chart work together by default in the eck-stack chart.
        fullnameOverride: elasticsearch

      # If enabled, will use the eck-kibana chart and deploy a Kibana resource.
      #
      eck-kibana:
        enabled: true
        spec:
          # This is also adjusting the kibana reference to the elasticsearch resource named previously so that
          # both the eck-elasticsearch and the eck-kibana chart work together by default in the eck-stack chart.
          elasticsearchRef:
            name: elasticsearch

      # If enabled, will use the eck-agent chart and deploy an Elastic Agent instance.
      #
      eck-agent:
        enabled: false

      # If enabled, will use the eck-fleet-server chart and deploy a Fleet Server resource.
      #
      eck-fleet-server:
        enabled: false

      # If enabled, will use the eck-beats chart and deploy a Beats resource.
      #
      eck-beats:
        enabled: false

      # If enabled, will use the eck-logstash chart and deploy a Logstash resource.
      #
      eck-logstash:
        enabled: false

      # If enabled, will use the eck-apm-server chart and deploy a standalone APM Server resource.
      #
      eck-apm-server:
        enabled: false

2024-05-22 14:04 UTC, JPedro2 commented on packs/elastic-stack-0.10.0/values.yaml
All done and tested. Had to remove the APM Preset for now as it gives a helm chart error when applied:
`*admission webhook "elastic-apm-validation-v1.k8s.elastic.co" denied the request: ApmServer.apm.k8s.elastic.co "elastic-stack-eck-stack-eck-apm-server" is invalid: metadata.name: Too long: must have at most 36 bytes`

2024-05-23 17:16 UTC, vishwanaths approved these changes

2024-05-23 18:03 UTC, zulfilee approved these changes

2024-05-23 18:12 UTC, merged